### PR TITLE
Update networkx version.

### PR DESCRIPTION
**Pull request by glassnotes**
The build pipeline on the `dev` branch is currently failing for some demos due to  the error 
```
networkx.exception.NetworkXError: random_state_index is incorrect
```

It looks like this was a known issue in a recent release and has been fixed in version `2.5.1` (see [here](https://github.com/networkx/networkx/issues/4722) and [here](https://github.com/networkx/networkx/issues/4718)). The `qml` repo specifies `networkx==2.4` so we can try updating this to see if it helps (and hopefully it will not cause other issues in the meantime).

### CODE REVIEW

**Comment by josh146** [comment]
It's super weird that NX 2.4, which used to work, suddenly became affected by this bug 🤔 Maybe one of the plugins has a dependency that was updating the NX version?

**Comment by josh146** [comment]
@glassnotes it worked! no more NX errors (other errors remain though). Once the CI is done I'll merge it in.

**Comment by glassnotes** [comment]
> @glassnotes it worked! no more NX errors (other errors remain though). Once the CI is done I'll merge it in.

Thanks for taking a look @josh146 !  I was wondering if it was related to PL itself - its  `requirements.txt` doesn't explicitly specify a version for `networx`, so I thought maybe it was pulling the most recent one and that was being propagated here (?). In any case, looks like remaining errors are just related to PL changes which are being addressed in the other PRs so we're good to go. Feel free to merge in :)

**Comment by josh146** [comment]
> its requirements.txt doesn't explicitly specify a version for networx, so I thought maybe it was pulling the most recent one and that was being propagated here (?)

The pinning in this repo should override any package specific requests though 🤔

**Pull request merged**
