### PR TITLE
[WIP] Add "start here" banner on main demo page

### PR DESCRIPTION
**Pull request by glassnotes**
**Title:** Add "start here" banner on main demo page

**Summary:** A simple implementation using a dropdown admonition that suggests a starting point for new users. 

**Relevant references:** None

**Possible Drawbacks:** Not as relevant after categorization during the re-design, but still nice to have for people who land on the demo page for the first time. Also we'll need to tweak the CSS if we decide to keep this. 

**Related GitHub Issues:** #83

### CODE REVIEW

**Comment by josh146** [comment]
Thanks @glassnotes! Since this is still marked as a draft, I've left some general high-level comments.

* I really like the contents, especially the link to installation!

* Should we also include a link to the 'quickstart guides'? E.g., "Begin with our PennyLane quickstart guides, then start by training a quantum circuit to rotate a qubit , or tune a beamsplitter!"

* The style and color look a bit out of place to me compared to the rest of the website 🤔 

* I thought the toggling was a good idea when we discussed it previously, but now that I can play around with it in practice, it seems a bit distracting. Since it's only a single sentence, better to keep it visible?

* I'm also wondering if it makes the demo page a bit too busy. What do you think about instead placing it on the index page directly? e.g.,

  image

  With the new demo landing page, the index page is a bit emptier now, and so maybe this is a better place for it

**Comment by glassnotes** [comment]
Oh I like that version much better! It is more likely that this is the first page people see, rather than the demo page, so I think it makes sense to have it up front.

As for the toggle, I found it is not very smooth, the text and links don't appear at the same time and the toggle button is not aligned with the text. I'm sure that can all be fixed through CSS sorcery, but if it goes on the front page like your example it doesn't need to be toggleable.

**Comment by glassnotes** [comment]
So the more I tinker with this, the less I think it's necessary. Someone who goes to the main page will see "what is QML" up front, which naturally leads people to the demos through a link at the bottom. Most of the stuff on "key concepts" also links to a demo. And the demo page itself now clearly highlights the basic demos and says "begin your journey...". @josh146 if you're cool with it maybe we just close down #83 and this PR for now.

**Comment by josh146** [comment]
> @josh146 if you're cool with it maybe we just close down #83 and this PR for now.

Yep convinced :+1:

The original feedback ("it is hard to find where to start") dates from before the (a) demo landing page, and (b) demo categorization.

Perhaps we can even argue that the demo landing page satisfies/fixes #83.

**Comment by glassnotes** [comment]
If it's just "where do I start", then I think the demo landing page takes care of #83. 

However this leads directly to the question  "where do I go next". This is partially addressed by the related demo links in the sidebar, but eventually it would be nice to have some recommended paths laid out. We can make a separate issue for that and think about where to put it - maybe it is a similar light green box with a couple ordered suggestions, sitting on the "basic demos" page.

**Comment by josh146** [comment]
:+1:

Another suggestion is to have navigation hints at the bottom of the demo. This could be as simple as 'Previous/Next demo', or more complicated (Enjoyed this demo? Check out these related demos <thumbnail> <thumbnail> <thumbnail>)

**Comment by glassnotes** [comment]
Yeah for sure! I'm gonna close these two things then, and set up a new issue for the new ideas.

**Pull request closed without merging**
