### PR TITLE
QubitDevice removed from toplevel, along with their warnings

### PR DESCRIPTION
**Pull request by JerryChen97**
**Title:**
Remove QubitDevice warnings, which will be removed in the 0.40PL
**Summary:**
as title
**Relevant references:**
#https://github.com/PennyLaneAI/pennylane/pull/6537
**Possible Drawbacks:**
None
**Related GitHub Issues:**

### CODE REVIEW

**Review by mudit2812 — CHANGES_REQUESTED** [review]
The warning filter from `conf.py` also needs to be removed.

Just a note that this PR should not be merged until the removal in PennyLane is merged.

**Review by mudit2812 — APPROVED** [review]

**Comment by albi3ro** [comment]
Do we know if blue qubit has updated their device to accommodate this removal?

**Comment by mudit2812** [comment]
> Do we know if blue qubit has updated their device to accommodate this removal?

@albi3ro , I messaged them on our slack channel when the deprecation first happened to let them know. They said they would resolve it, but I'm not sure if they have or not. I'll check in.

**Comment by mudit2812** [comment]
@JerryChen97 the blue qubit device has been fixed, so this PR can be merged now.

**Review by Alex-Preciado — APPROVED** [review]

**Pull request merged**
