### PR TITLE
learning2learn executable

### PR DESCRIPTION
**Pull request by KetpuntoG**
This PR is intended to convert the `learning2learn` demo to an executable demo

### CODE REVIEW

**Review by isaacdevlugt — COMMENTED** [review]
Looks good but there are math issues

Screenshot 2023-08-23 at 4 04 50 PM

**Comment by KetpuntoG** [comment]
> Looks good but there are math issues
> 
> Screenshot 2023-08-23 at 4 04 50 PM

Oh that's weird, can you reload the page? 

Captura de pantalla 2023-08-23 a las 16 10 46

**Review by isaacdevlugt — APPROVED** [review]
Math errors are gone. Not sure what happened 🤔. LGTM!

**Review by ikurecic — APPROVED** [review]
@KetpuntoG I'd probably change the 'last updated' line in the PY file. Otherwise, I _think_ everything is good like this. :)

**Comment by KetpuntoG** [comment]
> @KetpuntoG I'd probably change the 'last updated' line in the PY file. Otherwise, I _think_ everything is good like this. :)

I have thought about it but it doesn't really change anything for the user point of view. That's why I decided to leave it. Do you think it should be changed in that case?

**Comment by ikurecic** [comment]
You're right about the content, but the URL will change, right?
I've seen at least one research paper that I can remember off the top of my head that referenced that demo. So I would say this is a modification. Actually, maybe you should check about the URL change with Alex.

**Pull request merged**
