### PR TITLE
Update Pytorch and noisy devices demo in preparation for 0.27

### PR DESCRIPTION
**Pull request by trbromley**
Note, we should revisit whether the following makes sense to run on a computer that does not have a GPU:
```python
phi = Variable(torch.tensor(1.0, device="cuda"), requires_grad=True)
theta = Variable(torch.tensor(0.05, device="cuda"), requires_grad=True)
```
I get an error on my laptop.

### CODE REVIEW

**Review by Jaybsoni — APPROVED** [review]
Looks good to me 👍🏼. Is this device no longer active?

**Comment by Jaybsoni** [comment]
> Note, we should revisit whether the following makes sense to run on a computer that does not have a GPU:
> 
> ```python
> phi = Variable(torch.tensor(1.0, device="cuda"), requires_grad=True)
> theta = Variable(torch.tensor(0.05, device="cuda"), requires_grad=True)
> ```
> 
> I get an error on my laptop.

Were you able to run it elsewhere?

**Comment by josh146** [comment]
Note this is a really old demo, written around PL ~0.3 when we only had 5 or so demos. The purpose was to show that hybrid GPU-QPU computing is possible with PennyLane

**Comment by josh146** [comment]
So less about wanting users to use a GPU specifically, and more about having at least one demo to show how to do it/that it is possible

**Pull request merged**
