### PR TITLE
Demonstrations metadata updates

### PR DESCRIPTION
**Pull request by BM7878**
Adding metadata for five files that previously lacked it.

One file is a supplementary page to another demonstration. Whether this can be considered a 'true' demonstration in its own right is debatable, but unless it has a metadata file, it won't get served on the site, so I've added one for now.

Two files are for demonstrations published very recently.

### CODE REVIEW

**Review by ashishks0522 — APPROVED** [review]
Thanks @BM7878!

**Review by rashidnhm — COMMENTED** [review]
Do we want to move the metadata categories to the demonstrations folder as part of this PR?

**Review by ikurecic — APPROVED** [review]
lgtm

**Comment by BM7878** [comment]
> 

Yep, done.

**Pull request merged**
