### PR TITLE
Bump Python version to 3.10. Bump Poetry version to 1.7.1

### PR DESCRIPTION
**Pull request by rashidnhm**
**Title:** Bump Python Build version of QML to Python 3.10

**Summary:**
This PR drops Python 3.9 from QML and upgrades all CI to use 3.10 for building. This ensures compatibility with more packages including pennylane itself.

**Relevant references:**
[sc-51655](https://app.shortcut.com/xanaduai/story/51655/attempt-to-build-qml-using-python-3-10)

**Possible Drawbacks:**
There could potentially be rendering issues with react as the version of sphinx has been bumped from 4.0 to 4.3 (that is the lowest version of sphinx compatible with Python 3.10).

One issue that has been spotted so far within this PR as pointed out in [this linked comment](https://github.com/PennyLaneAI/qml/pull/996#issuecomment-1850384516) is table being missing in the `tutorial_photonics` demo. It seems in the earlier version of sphinx, a malformed table would raise a warning but still render, but that behaviour changed in 4.3 where the warning is raised but no table is rendered. 

There is also another UI bug where the related content field is misaligned, see image below:

image

However, this issue is not related to this PR, and @ashishks0522 has opened a PR XanaduAI/pennylane.ai-react#845 to address it.

Due to the fact that there does not exist any automated manner of validating rendered demos. If a bug is encountered that could be due to this PR, it would need to be addressed on a per issue basis.

**Related GitHub Issues:**
None.

### CODE REVIEW

**Review by albi3ro — APPROVED** [review]

**Comment by timmysilv** [comment]
why did poetry need bumping? might affect my poetry PR too : ) other than that, this seems fine to me!

**Comment by rashidnhm** [comment]
Hello all, 

It seems some demos are not rendering as expected on this PR, take a look at `tutorial_photonics`:

- [This PR](https://qml-build-previews.pennylane.ai/pull_request_build_preview/996/qml/demos/tutorial_photonics/#gaussian-operations)
- [Production](https://pennylane.ai/qml/demos/tutorial_photonics/#gaussian-operations)

There is a table missing under the Gaussian Operations header .. let me do a more fine combed look through all the demos .. in the meantime, I will add `do not merge` to this PR

**Review by timmysilv — APPROVED** [review]
I am a little worried that we have not found all of the little bugs like the table one you spotted. that said, it's a daunting task to manually validate every single demo. I would be fine with alerting the demos channel to keep an eye out and just do it, but I'd suggest getting buy-in there first. I'm open to slowing this down if there is no rush, and validating things a bit more carefully, but I don't want to block this upgrade

**Review by ashishks0522 — APPROVED** [review]
From what all I could verify, demos look the same. Thanks @rashidnhm!

**Comment by rashidnhm** [comment]
Making this comment for historical purposes.

As noted by @timmysilv it is far too time consuming to manually validate every single demo.

The approach taken to validate the changes for this PR was to ensure the elements within a demo were correct, and validate said element across a random batch of demos. For example, take static images, if 6 demos are picked at random and all the static images within them are rendering correctly, we can say with high level of confidence that the static image linking is working as expected.

That being said, the following things were checked across a handful of demos:
- Tables
- Images
- Thumbnails
- Math equations
- Headers
- Hyperlinks
- Graphs
- Plots
- codeblocks
- lists
- Admonition
- Links and references

Shoutout goes to @ashishks0522 for helping with these validations! :tada: 

It is still possible that a few UI bugs may have fallen through the cracks, but as stated in the description of the PR, those will need to be handled on a per bug basis.

**Pull request merged**
