### PR TITLE
Replace deprecated X and P

### PR DESCRIPTION
**Pull request by lillian542**
The CV observables `qml.X` and `qml.P` will be renamed in PL v0.32 as `qml.QuadX` and `qml.QuadP`, and usage of `qml.X` and `qml.P` will be deprecated and raise a warning.

This PR replaces instances of `X` and `P` observables in the demos with `QuadX` and `QuadP`

Won't pass tests/can't merge until [deprecation PR in PennyLane](https://github.com/PennyLaneAI/pennylane/pull/4330) repo is completed and merged.

### CODE REVIEW

**Comment by lillian542** [comment]
[sc-39024]

**Comment by KetpuntoG** [comment]
Thanks for open this 🙌

**Comment by lillian542** [comment]
@KetpuntoG The build fails because `AttributeError: module 'pennylane' has no attribute 'QuadX'`. The PR introducing `QuadX` has been merged into master, and I can access `qml.QuadX` in a Jupyter notebook from the master branch. 

Am I supposed to target the `dev` branch of the `qml` repo for this PR instead? Or is there some other problem I need to fix?

**Comment by josh146** [comment]
@lillian542 yep, PRs needing the dev version of PL should use the `dev` branch here.

**Comment by KetpuntoG** [comment]
One question @josh146 , do we merge to dev? 
Or should I wait for the new PL version to be release and point the branch to master

**Review by timmysilv — APPROVED** [review]
good catch! idk if we have our own deprecation guide yet, I remember hearing grumblings, but perhaps we should formally advise people deprecating things to check qml + plugins as well

**Review by KetpuntoG — APPROVED** [review]
Nice!

**Pull request merged**
