### PR TITLE
testing style

### PR DESCRIPTION
**Pull request by KetpuntoG**
Pl style of matplotlib does not work in the repository. 
Testing locally has shown that updating matplotlib does work.

### CODE REVIEW

**Comment by timmysilv** [comment]
can you re-run CI with the build-all-demos label? bumping matplotlib is a major change for qml, I just wanna make sure everything still works as expected

**Comment by KetpuntoG** [comment]
> can you re-run CI with the build-all-demos label? bumping matplotlib is a major change for qml, I just wanna make sure everything still works as expected

Oh good point!!

**Review by timmysilv — APPROVED** [review]
awesome! would probably take too long to spot-check every demo, but the fact that they all built is pretty good imo

**Comment by KetpuntoG** [comment]
> awesome! would probably take too long to spot-check every demo, but the fact that they all built is pretty good imo

I have tested 15 random demos and everything seems to be fine

**Review by ikurecic — APPROVED** [review]
Nice! Thanks for checking everything, @KetpuntoG , glad it works with a higher version. :)
This looks good to me!

**Pull request merged**
