### PR TITLE
Cleaning files

### PR DESCRIPTION
**Pull request by KetpuntoG**
This PR is a copy of [this one](https://github.com/PennyLaneAI/qml/pull/876). Initially it was pointing at dev to see that nothing was broken and now we are pointing at master

### CODE REVIEW

**Review by ashishks0522 — APPROVED** [review]
Since its working in dev, looks good!

P.S. Tagging relevant people to review these deletion changes

**Comment by ottoak** [comment]
Thanks for this @KetpuntoG!

Question re: the assets held in `_static`, e.g. `_static/datasets` - with the removal of those pages from here, do these images go too? E.g. are they now held in the react repo?

**Comment by ashishks0522** [comment]
> Thanks for this @KetpuntoG!
> 
> Question re: the assets held in `_static`, e.g. `_static/datasets` - with the removal of those pages from here, do these images go too? E.g. are they now held in the react repo?

Yes for `/datasets` they are present in react repo directly and not sourced from here

**Comment by josh146** [comment]
Looks good to me! Although how come the PR preview didn't work for this PR?

**Review by BM7878 — APPROVED** [review]

**Comment by KetpuntoG** [comment]
> Looks good to me! Although how come the PR preview didn't work for this PR?

If I am not mistaken, now only those changes that affect a demo will be deployed. 
If you want to load everything, you can set the `build-all-qml-demos`

**Comment by ottoak** [comment]
> > Thanks for this @KetpuntoG!
> > Question re: the assets held in `_static`, e.g. `_static/datasets` - with the removal of those pages from here, do these images go too? E.g. are they now held in the react repo?
> 
> Yes for `/datasets` they are present in react repo directly and not sourced from here

Okay cool - @KetpuntoG @ashishks0522 do you want to clean up the image assets then, or do that in a separate PR?

**Comment by KetpuntoG** [comment]
> > > Thanks for this @KetpuntoG!
> > > Question re: the assets held in `_static`, e.g. `_static/datasets` - with the removal of those pages from here, do these images go too? E.g. are they now held in the react repo?
> > 
> > 
> > Yes for `/datasets` they are present in react repo directly and not sourced from here
> 
> Okay cool - @KetpuntoG @ashishks0522 do you want to clean up the image assets then, or do that in a separate PR?

I'll do it in a different PR 👍

**Pull request merged**
