### PR TITLE
[WIP] Enable tape mode for "Quantum gradients with backpropagation"

### PR DESCRIPTION
**Pull request by thisac**
Enables tape mode for "Quantum gradients with backpropagation".

It fails with the error:
```
Traceback (most recent call last):
  File "demonstrations/tutorial_backprop.py", line 368, in <module>
    r = tape.gradient(res, params)
  File "/home/theodor/miniconda3/envs/qml/lib/python3.7/site-packages/tensorflow/python/eager/backprop.py", line 1048, in gradient
    unconnected_gradients=unconnected_gradients)
  File "/home/theodor/miniconda3/envs/qml/lib/python3.7/site-packages/tensorflow/python/eager/imperative_grad.py", line 77, in imperative_grad
    compat.as_str(unconnected_gradients.value))
  File "/home/theodor/miniconda3/envs/qml/lib/python3.7/site-packages/tensorflow/python/ops/custom_gradient.py", line 448, in actual_grad_fn
    "gradients but returned", len(flat_grads), "instead.")
ValueError: ('custom_gradient function expected to return', 1, 'gradients but returned', 12, 'instead.')
```

### CODE REVIEW

**Comment by josh146** [comment]
@thisac, maybe I'm missing it, but all checks pass? And the demo output seems correct? https://2343-214003948-gh.circle-artifacts.com/0/_build/html/demos/tutorial_backprop.html

**Comment by josh146** [comment]
I ran it locally and it also seems okay 🤔

**Comment by josh146** [comment]
@thisac still passing 🤔 Does TF 2.4 solve it for you?

**Comment by thisac** [comment]
> @thisac still passing thinking Does TF 2.4 solve it for you?

Yes, the issue was that I was running TF 2.2. It passes with TF 2.4, so I'll close this PR. Thanks @josh146!

**Pull request closed without merging**
