### PR TITLE
Remove interactive demo test

### PR DESCRIPTION
**Pull request by josh146**

### CODE REVIEW

**Comment by KetpuntoG** [comment]
Hey @josh146 , what does this PR do?

**Comment by josh146** [comment]
@KetpuntoG this deletes the Fourier explainer demo from the `dev` branch, where it currently lives :)

**Comment by KetpuntoG** [comment]
Ah I see! Now that the other demo has been created, it is ready to be deleted, right? :)

**Comment by josh146** [comment]
yep!

**Review by KetpuntoG — APPROVED** [review]

**Review by branedrane — APPROVED** [review]

**Pull request merged**
