### PR TITLE
DO NOT MERGE (yet): Changing internal authors' ids to usernames

### PR DESCRIPTION
**Pull request by ikurecic**
As described [here](https://www.notion.so/xanaduai/Linking-Profile-Content-Updates-e1b608c006484031b021620f2307e1a8)

## Note
- Blocked by https://github.com/XanaduAI/pennylane.ai-react/pull/1618

### CODE REVIEW

**Comment by Lorraine-at-Xanadu** [comment]
Thank you for doing this, @ikurecic.

1. I added @Mandrenkov and @ashishks0522 as reviewers.
2. Could you please add the note `DO NOT MERGE` to this PR since it's dependent upon the implementation that @ashishks0522 is currently working on?
3. @ashishks0522 - Will you merge this PR when you're ready? Note that @ikurecic will be OOO on vacation August 7–13.

cc @justinpickering

**Review by Lorraine-at-Xanadu — APPROVED** [review]
LGTM. Thank you very much, @ikurecic.

**Review by justinpickering — APPROVED** [review]
Thank you @ikurecic !

Linking the related shortcut ticket here: https://app.shortcut.com/xanaduai/story/62151/add-usernames-to-demo-author-metadata.

**Comment by Mandrenkov** [comment]
For posterity: [sc-62151].

**Review by Mandrenkov — APPROVED** [review]

**Review by ashishks0522 — APPROVED** [review]

**Pull request merged**
