### PR TITLE
Update Autograd Requirement

### PR DESCRIPTION
**Pull request by AmintorDusko**
**Title:** Update Autograd Requirement.

**Summary:** Upgrading Autograd version to keep up with the Numpy deprecation cycle. 
This PR also unpin the numpy version.

**Relevant references:** 

**Possible Drawbacks:**

**Related GitHub Issues:**

### CODE REVIEW

**Comment by josh146** [comment]
@AmintorDusko I've added the `#ignore-qml-cache` label -- this will force the PR to build _all_ demos from scratch, to ensure it still works. However, you may need to push a new commit to enable this!

**Comment by AmintorDusko** [comment]
Hi @josh146, We can see that the building is falling because of the numpy version restriction on PennyLane. I'm preparing a PR there to remove it.

**Comment by AmintorDusko** [comment]
We can't unpin the numpy version on PennyLane because numpy removed support for ragged arrays.
I will downgrade the numpy minimal version here.

**Review by josh146 — APPROVED** [review]
Thank you @AmintorDusko!

**Pull request merged**
