### PR TITLE
Updated 'What is QML' file name, switched images

### PR DESCRIPTION
**Pull request by ikurecic**
In preparation for the PennyLane website update. Second image will be completed and switched out later.

### CODE REVIEW

**Review by BM7878 — DISMISSED** [review]

**Review by josh146 — CHANGES_REQUESTED** [review]
Thanks @ikurecic! Only one request here, could you rename `the page back to `whatisqml.rst`?

This is because the name of the rst file becomes the URL, and we want to preserve the same URL for search purposes

**Comment by ikurecic** [comment]
@josh146 I thought the solution was that we'd double up the pages, run both whatisqml.html and what-is-quantum-machine-learning.html for a few months. I can return it, or make duplicates from here, or leave that to the dev end of things?

**Comment by BM7878** [comment]
Search engines might not look favourably on us for doubling-up the pages. Let's keep the current file name & URL for now - we'll do the change later (along with a few other pages) and set up a redirect.

**Review by josh146 — DISMISSED** [review]
💯

**Comment by Anakhom** [comment]
Closing as changes are implemented in https://github.com/PennyLaneAI/qml/pull/682

**Pull request closed without merging**
