### PR TITLE
Update demos to make use of the new qml.sample and qml.expval(H) func, merge into master! 

### PR DESCRIPTION
**Pull request by Jaybsoni**
Adding the changes merged into dev also into master (#330)

### CODE REVIEW

**Review by antalszava — APPROVED** [review]
Thank you! :pray:

**Review by josh146 — APPROVED** [review]
🍒 ⛏️

**Comment by josh146** [comment]
Looks like the VQE-QNG demo is dependent on a bug fix in master! https://app.circleci.com/pipelines/github/PennyLaneAI/qml/4025/workflows/4975ed6e-72b0-4d35-ba73-ca274e5db33e/jobs/4275

Maybe we just undo the changes on this tutorial @Jaybsoni  (via `git checkout master demonstrations/tutorial_vqe_qng.py`), and we leave that one updated in the `dev` branch but not the `master` branch :)

**Comment by Jaybsoni** [comment]
> Looks like the VQE-QNG demo is dependent on a bug fix in master! https://app.circleci.com/pipelines/github/PennyLaneAI/qml/4025/workflows/4975ed6e-72b0-4d35-ba73-ca274e5db33e/jobs/4275
> 
> Maybe we just undo the changes on this tutorial @Jaybsoni (via `git checkout master demonstrations/tutorial_vqe_qng.py`), and we leave that one updated in the `dev` branch but not the `master` branch :)

I think it might be worse than that 😢, I just ran the same demo on the update_demos branch which was merged into dev, locally, and I got the same error. Somehow it fell through the crack when I was testing locally and I marked it as working? Looking into it right now. I might also just run all of the demos changed again to make triple sure that everything is working as expected. Surprised it didnt get caught in the CI check for the dev branch

**Comment by josh146** [comment]
> Im not sure what exactly happened but it seems to working again locally on my device when using the update_demos branch which was merged into dev... ! Thankfully I must have not really switched branches when I re-ran it earlier (^^). I can revert the changes as suggested.

Nice! Looks like it's working, feel free to merge it in :)

**Pull request merged**
