### PR TITLE
Fix deprecation warnings in dev build

### PR DESCRIPTION
**Pull request by astralcai**
Fixing deprecation warnings in the latest dev build.
- Replace `expansion_strategy` with `level`.

### CODE REVIEW

**Comment by astralcai** [comment]
[sc-71204]

**Review by Shiro-Raven — CHANGES_REQUESTED** [review]
Code changes look good to me! Please just visually verify that the outputs are still the same. We shouldn't be expecting any discrepancies with the new argument.

**Review by albi3ro — APPROVED** [review]
👍

**Review by Shiro-Raven — APPROVED** [review]
Don't forget to black the files. Thanks!

**Pull request merged**
