### PR TITLE
Switch from `IBMQ` to `IBMProvider` in tutorials

### PR DESCRIPTION
**Pull request by frederikwilde**
**Summary:**
`qiskit` has deprecated support for `qiskit.IBMQ` for access management in January 2023. `pennylane-qiskit` has therefore switched to using the new access management provided by `qiskit_ibm_provider.IBMProvider`, which stores account data in `$HOME/.qiskit/qiskit-ibm.json` instead of `$HOME/.qiskit/qiskitrc`, which was used by `qiskit.IBMQ`.

In some tutorials the use of `qiskit.IBMQ` is still displayed. This results in errors when running the tutorial. A minimal error of such a kind is
```Python
from qiskit import IBMQ
import pennylane as qml

IBMQ.save_account(my_token)  # stores account data into ~/.qiskit/qiskitrc which will not be found by pennylane-qiskit
device = qml.device("qiskit.ibmq", wires=[0, 1])
```
which results in
```Python
Traceback (most recent call last):
  File "/Users/frederik.wilde/qml/ibm_account_error.py", line 5, in <module>
    device = qml.device("qiskit.ibmq", wires=[0, 1])
  File "/Users/frederik.wilde/pennylane/pennylane/__init__.py", line 337, in device
    dev = plugin_device_class(*args, **options)
  File "/Users/frederik.wilde/qml/venv/lib/python3.9/site-packages/pennylane_qiskit/ibmq.py", line 77, in __init__
    connect(kwargs)
  File "/Users/frederik.wilde/qml/venv/lib/python3.9/site-packages/pennylane_qiskit/ibmq.py", line 138, in connect
    raise IBMAccountError("No active IBM Q account, and no IBM Q token provided.")
qiskit_ibm_provider.exceptions.IBMAccountError: 'No active IBM Q account, and no IBM Q token provided.'
```
along with the deprecation warnings for `IBMQ`.

This PR updates the tutorials where needed to teach the user to use `qiskit_ibm_provider.IBMProvider`.

**Relevant references:**
https://github.com/Qiskit/qiskit-ibmq-provider

**Possible Drawbacks:**
People who still have their account data stored in `$HOME/.qiskit/qiskitrc` will need to store their account again using the new method.

**Related GitHub Issues:**
n/a

### CODE REVIEW

**Comment by KetpuntoG** [comment]
Thanks for this @frederikwilde ! Is it ready for review?

**Comment by frederikwilde** [comment]
Yes, it's ready for review.

**Review by KetpuntoG — COMMENTED** [review]
Nice! I think this one should also be updated
https://pennylane.ai/qml/demos/ensemble_multi_qpu

**Comment by frederikwilde** [comment]
Hm, I think it should work as it is. When I try to run the tutorial locally I get a connection error from the Rigetti device:

```Python
ConnectError                              Traceback (most recent call last)
File ~/qml/demonstrations/ensemble_multi_qpu.py:176
    139 ##############################################################################
    140 # .. figure:: /demonstrations/ensemble_multi_qpu/ensemble_multi_qpu_001.png
    141 #    :width: 80%
   (...)
    171 #
    172 # We begin by defining the two quantum devices and the circuits to be run on them.
    174 n_wires = 4
--> 176 dev0 = qml.device("rigetti.qvm", device="4q-qvm")
    177 dev1 = qml.device("qiskit.aer", wires=4)
    178 devs = [dev0, dev1]

File ~/pennylane/pennylane/__init__.py:337, in device(name, *args, **kwargs)
    331     raise DeviceError(
    332         f"The {name} plugin requires PennyLane versions {plugin_device_class.pennylane_requires}, "
    333         f"however PennyLane version {__version__} is installed."
    334     )
    336 # Construct the device
--> 337 dev = plugin_device_class(*args, **options)
    339 # Once the device is constructed, we set its custom expansion function if
    340 # any custom decompositions were specified.
    341 if custom_decomps is not None:

File ~/qml/venv/lib/python3.9/site-packages/pennylane_rigetti/qvm.py:74, in QVMDevice.__init__(self, device, shots, wires, noisy, **kwargs)
     70     raise ValueError("QVM device cannot be used for analytic computations.")
     72 self.noisy = noisy
---> 74 super().__init__(
     75     device, wires=wires, shots=shots, noisy=noisy, active_reset=False, **kwargs
     76 )

File ~/qml/venv/lib/python3.9/site-packages/pennylane_rigetti/qc.py:95, in QuantumComputerDevice.__init__(self, device, shots, wires, active_reset, **kwargs)
     90     """dict[str, pyquil.quilatom.MemoryReference]: stores the string of symbolic
     91         parameters associated with their PyQuil memory references."""
     93 timeout_args = self._get_timeout_args(**kwargs)
---> 95 self.qc = self.get_qc(device, **timeout_args)
     97 self.num_wires = len(self.qc.qubits())
     99 if wires is None:
    100     # infer the number of modes from the device specs
    101     # and use consecutive integer wire labels

...  # Many more traces. Let me know if you want them.

ConnectError: [Errno 61] Connection refused
```

**Comment by KetpuntoG** [comment]
> Hm, I think it should work as it is. When I try to run the tutorial locally I get a connection error from the Rigetti device:
> 
> ```python
> ConnectError                              Traceback (most recent call last)
> File ~/qml/demonstrations/ensemble_multi_qpu.py:176
>     139 ##############################################################################
>     140 # .. figure:: /demonstrations/ensemble_multi_qpu/ensemble_multi_qpu_001.png
>     141 #    :width: 80%
>    (...)
>     171 #
>     172 # We begin by defining the two quantum devices and the circuits to be run on them.
>     174 n_wires = 4
> --> 176 dev0 = qml.device("rigetti.qvm", device="4q-qvm")
>     177 dev1 = qml.device("qiskit.aer", wires=4)
>     178 devs = [dev0, dev1]
> 
> File ~/pennylane/pennylane/__init__.py:337, in device(name, *args, **kwargs)
>     331     raise DeviceError(
>     332         f"The {name} plugin requires PennyLane versions {plugin_device_class.pennylane_requires}, "
>     333         f"however PennyLane version {__version__} is installed."
>     334     )
>     336 # Construct the device
> --> 337 dev = plugin_device_class(*args, **options)
>     339 # Once the device is constructed, we set its custom expansion function if
>     340 # any custom decompositions were specified.
>     341 if custom_decomps is not None:
> 
> File ~/qml/venv/lib/python3.9/site-packages/pennylane_rigetti/qvm.py:74, in QVMDevice.__init__(self, device, shots, wires, noisy, **kwargs)
>      70     raise ValueError("QVM device cannot be used for analytic computations.")
>      72 self.noisy = noisy
> ---> 74 super().__init__(
>      75     device, wires=wires, shots=shots, noisy=noisy, active_reset=False, **kwargs
>      76 )
> 
> File ~/qml/venv/lib/python3.9/site-packages/pennylane_rigetti/qc.py:95, in QuantumComputerDevice.__init__(self, device, shots, wires, active_reset, **kwargs)
>      90     """dict[str, pyquil.quilatom.MemoryReference]: stores the string of symbolic
>      91         parameters associated with their PyQuil memory references."""
>      93 timeout_args = self._get_timeout_args(**kwargs)
> ---> 95 self.qc = self.get_qc(device, **timeout_args)
>      97 self.num_wires = len(self.qc.qubits())
>      99 if wires is None:
>     100     # infer the number of modes from the device specs
>     101     # and use consecutive integer wire labels
> 
> ...  # Many more traces. Let me know if you want them.
> 
> ConnectError: [Errno 61] Connection refused
> ```

There is a not that says about use IBMQ, should it be updated?

**Comment by frederikwilde** [comment]
You mean this note, right?
Screenshot 2023-07-07 at 9 54 54 AM
This should work as expected, as long as the IBMQ token is stored correctly. However, the docs page that is linked is outdated. I'll create a separate PR for this.

**Comment by frederikwilde** [comment]
Oh wait, the link refers to the docs of a different `pennylane-qiskit` repo: https://github.com/carstenblank/pennylane-qiskit
Here it is explained correctly: https://docs.pennylane.ai/projects/qiskit/en/latest/devices/ibmq.html
I changed the link. Now something went wrong with rebasing.

**Review by CatalinaAlbornoz — APPROVED** [review]
Thank you so much for making these updates @frederikwilde !!! 🚀 🚀 🚀

**Review by KetpuntoG — APPROVED** [review]

**Pull request merged**
